site_name: "GSOC: Carlos Falgueras García"

pages:
        - Home: index.md
        - My work:
                - Features:
                        - Rule deletion: rule-deletion.md
                        - TLV Infrastructure: tlv-infrastructure.md
                        - Rule replacement: rule-replacement.md
                - Small Features: small-features.md
                - Fixes: fixes.md
                - List of commits: commits.md
        - My activity: activity.md

theme: slate
